apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-backend
spec:
  replicas: 1

  selector:
    matchLabels:
      app: taskboard-backend

  template:
    metadata:
      labels:
        app: taskboard-backend

    spec:
      containers:
      - name: backend
        image: taskboard-backend
        imagePullPolicy: Never

        ports:
        - containerPort: 8000
